/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TachesRouteImport } from './routes/taches'
import { Route as StagiairesRouteImport } from './routes/stagiaires'
import { Route as ScanQrRouteImport } from './routes/scan-qr'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as PointageRouteImport } from './routes/pointage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AlertesRouteImport } from './routes/alertes'
import { Route as IndexRouteImport } from './routes/index'

const TachesRoute = TachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => rootRouteImport,
} as any)
const StagiairesRoute = StagiairesRouteImport.update({
  id: '/stagiaires',
  path: '/stagiaires',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanQrRoute = ScanQrRouteImport.update({
  id: '/scan-qr',
  path: '/scan-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const PointageRoute = PointageRouteImport.update({
  id: '/pointage',
  path: '/pointage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertesRoute = AlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertes': typeof AlertesRoute
  '/login': typeof LoginRoute
  '/pointage': typeof PointageRoute
  '/projets': typeof ProjetsRoute
  '/rapports': typeof RapportsRoute
  '/scan-qr': typeof ScanQrRoute
  '/stagiaires': typeof StagiairesRoute
  '/taches': typeof TachesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertes': typeof AlertesRoute
  '/login': typeof LoginRoute
  '/pointage': typeof PointageRoute
  '/projets': typeof ProjetsRoute
  '/rapports': typeof RapportsRoute
  '/scan-qr': typeof ScanQrRoute
  '/stagiaires': typeof StagiairesRoute
  '/taches': typeof TachesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertes': typeof AlertesRoute
  '/login': typeof LoginRoute
  '/pointage': typeof PointageRoute
  '/projets': typeof ProjetsRoute
  '/rapports': typeof RapportsRoute
  '/scan-qr': typeof ScanQrRoute
  '/stagiaires': typeof StagiairesRoute
  '/taches': typeof TachesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertes'
    | '/login'
    | '/pointage'
    | '/projets'
    | '/rapports'
    | '/scan-qr'
    | '/stagiaires'
    | '/taches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertes'
    | '/login'
    | '/pointage'
    | '/projets'
    | '/rapports'
    | '/scan-qr'
    | '/stagiaires'
    | '/taches'
  id:
    | '__root__'
    | '/'
    | '/alertes'
    | '/login'
    | '/pointage'
    | '/projets'
    | '/rapports'
    | '/scan-qr'
    | '/stagiaires'
    | '/taches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertesRoute: typeof AlertesRoute
  LoginRoute: typeof LoginRoute
  PointageRoute: typeof PointageRoute
  ProjetsRoute: typeof ProjetsRoute
  RapportsRoute: typeof RapportsRoute
  ScanQrRoute: typeof ScanQrRoute
  StagiairesRoute: typeof StagiairesRoute
  TachesRoute: typeof TachesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taches': {
      id: '/taches'
      path: '/taches'
      fullPath: '/taches'
      preLoaderRoute: typeof TachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stagiaires': {
      id: '/stagiaires'
      path: '/stagiaires'
      fullPath: '/stagiaires'
      preLoaderRoute: typeof StagiairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-qr': {
      id: '/scan-qr'
      path: '/scan-qr'
      fullPath: '/scan-qr'
      preLoaderRoute: typeof ScanQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pointage': {
      id: '/pointage'
      path: '/pointage'
      fullPath: '/pointage'
      preLoaderRoute: typeof PointageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertes': {
      id: '/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertesRoute: AlertesRoute,
  LoginRoute: LoginRoute,
  PointageRoute: PointageRoute,
  ProjetsRoute: ProjetsRoute,
  RapportsRoute: RapportsRoute,
  ScanQrRoute: ScanQrRoute,
  StagiairesRoute: StagiairesRoute,
  TachesRoute: TachesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
